# Generated by Django 3.1 on 2020-09-08 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0002_auto_20200907_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='john',
            table='nearbyshops_john',
        ),
    ]
