# Generated by Django 3.1 on 2020-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0003_auto_20200908_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
