# Generated by Django 3.1 on 2020-09-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0004_review_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='john',
            options={'managed': True},
        ),
    ]
