# Generated by Django 3.1 on 2020-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0006_auto_20200913_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='john',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='zip_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
