# Generated by Django 3.1 on 2020-09-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0007_auto_20200913_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='john',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
