# Generated by Django 3.1 on 2020-09-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0009_auto_20200914_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='john',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
