# Generated by Django 3.0.8 on 2020-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200818_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Following'), (2, 'Blocked')], null=True),
        ),
    ]
