# Generated by Django 3.0.8 on 2020-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='details',
            field=models.TextField(default='Product details', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.FileField(default='image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='startDate',
            field=models.DateTimeField(default='2020-07-01 12:00'),
            preserve_default=False,
        ),
    ]
