# Generated by Django 3.0.8 on 2020-07-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200724_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='startDate',
        ),
    ]
