# Generated by Django 3.0.8 on 2020-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200724_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='details',
            field=models.TextField(default='details', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.FileField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
