# Generated by Django 3.0.8 on 2020-07-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200724_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.TextField(),
        ),
    ]
