# Generated by Django 3.0.8 on 2020-07-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200724_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='images',
            new_name='image',
        ),
    ]
