# Generated by Django 3.0.8 on 2020-07-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.Category'),
            preserve_default=False,
        ),
    ]
