# Generated by Django 3.0.8 on 2020-07-25 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200725_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
