# Generated by Django 3.0.8 on 2020-07-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200726_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingbids', to='auctions.Listing'),
        ),
    ]
