# Generated by Django 3.0.8 on 2020-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_bid_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateField(blank=True, default="2020-01-01"),
            preserve_default=False,
        ),
    ]
