# Generated by Django 3.0.8 on 2020-07-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200726_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listingbids', to='auctions.Bid'),
            preserve_default=False,
        ),
    ]
