# Generated by Django 3.0.8 on 2020-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200727_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2020-7-10'),
            preserve_default=False,
        ),
    ]
