# Generated by Django 3.0.8 on 2020-07-27 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to=settings.AUTH_USER_MODEL)),
                ('watchedListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingwatch', to='auctions.Listing')),
            ],
        ),
    ]
