# Generated by Django 3.0.8 on 2020-07-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20200729_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, related_name='listingbids', to='auctions.Listing'),
            preserve_default=False,
        ),
    ]
