# Generated by Django 3.0.8 on 2020-07-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20200729_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
