# Generated by Django 3.0.8 on 2020-07-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='startPrice',
        ),
    ]
